import{S as q,i as m,a as w}from"./assets/vendor-bad0427b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=c(e);fetch(e.href,s)}})();const S=document.querySelector("form"),d=document.querySelector("input"),u=document.querySelector(".gallery"),p=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");let r=1,g=40;const l=new URLSearchParams({key:"41708261-c154389f16c12e10553f8f229",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:g}),k=new q(".gallery a",{captionsData:"alt",captionDelay:250});S.addEventListener("submit",async t=>{t.preventDefault(),u.innerHTML="",n.style.display="none";const o=d.value.trim();if(d.value="",o)l.set("q",o),p.style.display="block",r=1,l.set("page",r),f();else{m.error({message:"Please enter your search query",position:"topRight"});return}});const y=async()=>(await w.get(`https://pixabay.com/api/?${l}`)).data,f=()=>y().then(({hits:t})=>{if(t&&t.length>0){const o=t.map(c=>{const{webformatURL:a,largeImageURL:e,tags:s,likes:i,views:h,comments:b,downloads:L}=c;return`<li class="gallery-item">
                            <a class="gallery-link" href="${e}">
                                <img
                                    class="gallery-image"
                                    src="${a}"
                                    alt="${s}"
                                />
                                <ul class="img-description">
                                    <li class="img-description-item">Likes<span class="img-description-item-num">${i}</span></li>
                                    <li class="img-description-item">Views<span class="img-description-item-num">${h}</span></li>
                                    <li class="img-description-item">Comments<span class="img-description-item-num">${b}</span></li>
                                    <li class="img-description-item">Downloads<span class="img-description-item-num">${L}</span></li>
                                </ul>
                            </a>
                        </li>`}).join("");u.insertAdjacentHTML("beforeend",o),k.refresh(),n.style.display="block",v(),r!==1&&P()}else m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(t=>{console.log(t)}).finally(()=>{p.style.display="none"});n.addEventListener("click",async()=>{r+=1,l.set("page",r),n.style.display="none",p.style.display="block",f()});const v=()=>{y().then(t=>{const o=Math.ceil(t.totalHits/g);r>=o&&(m.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.style.display="none")}).catch(t=>{console.log(t)})},P=async()=>{const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,left:100,behavior:"smooth"})};
//# sourceMappingURL=commonHelpers.js.map
